# Generated by Django 6.0.4 on 2026-04-25 06:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vk_id', models.BigIntegerField(unique=True, verbose_name='ID ВКонтакте')),
                ('full_name', models.CharField(max_length=255, verbose_name='ФИО / Никнейм')),
                ('phone', models.CharField(blank=True, max_length=20, null=True, verbose_name='Телефон')),
                ('total_spent', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Всего потрачено (₽)')),
                ('bot_state', models.CharField(default='START', max_length=50, verbose_name='Состояние бота (State)')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата регистрации')),
            ],
            options={
                'verbose_name': 'Клиент',
                'verbose_name_plural': 'Клиенты',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Material',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название материала')),
                ('price_per_meter', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='Цена за пог. метр (₽)')),
                ('in_stock', models.BooleanField(default=True, verbose_name='В наличии')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
            ],
            options={
                'verbose_name': 'Материал',
                'verbose_name_plural': 'Склад материалов',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='QuickReply',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Название шаблона')),
                ('text', models.TextField(verbose_name='Текст ответа')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активен')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
            ],
            options={
                'verbose_name': 'Быстрый ответ',
                'verbose_name_plural': 'Быстрые ответы',
                'ordering': ['title'],
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('NEW', 'Новое'), ('IN_PROGRESS', 'В работе'), ('READY', 'Готово'), ('CANCELLED', 'Отменено')], default='NEW', max_length=20, verbose_name='Статус')),
                ('description', models.TextField(blank=True, verbose_name='Описание заказа / ТЗ')),
                ('cut_length', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, verbose_name='Длина реза (м)')),
                ('layout_file', models.FileField(blank=True, null=True, upload_to='layouts/%Y/%m/', verbose_name='Файл макета')),
                ('final_price', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Итоговая цена (₽)')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата изменения')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='crm.client', verbose_name='Клиент')),
                ('material', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to='crm.material', verbose_name='Материал')),
            ],
            options={
                'verbose_name': 'Заказ',
                'verbose_name_plural': 'Заказы',
                'ordering': ['-created_at'],
            },
        ),
    ]
